<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="itext7" Version="9.7.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.6" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.12" />
	  <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AUTOCENTER.Domain\AUTOCENTER.Domain.csproj" />
    <ProjectReference Include="..\AUTOCENTER.Infra\AUTOCENTER.Infra.csproj" />
  </ItemGroup>

</Project>
